### ISSUE TITLE
Hi 终于碰到这个问题

### ISSUE THREAD

**Issue by zetaoWu** [dengyuhan/CameraPermissionCompat#1]
背景：.我也用的魅族pro(6.0)系统。 我当初的做法是先判断了Android M版，通过异常检测放在了小于6.0里面，然后噩梦，后台已经将权限禁止，通过checkSelfPremission返回的允许,懵逼。

简单说下我的问题：
1. 刚开始我也想通过手机型号判断 ，## 这个项目的代码小米兼容吗？。网上大都采用了AppOpsManager去配置（手头还没小米6.0版本,我看网上大都采用这个方式）
2.我这边还是直接检测没有权限的话，直接提示让他自己去手动设置中打开权限了。

**Comment by xiandanin** [comment]
我印象中是测过MIUI Android5.0和6.0  是适用的,你可以再试试
